apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: next-app
  app.kubernetes.io/instance: next-app-instance
  app.kubernetes.io/name: next-app
images:
- name: '*'
  newName: quay.io/rene_auberger/next-app
  newTag: 5a7223826744b366f93425deeb86686f417264ba
